package com.example.selftracker.repository

object DevIconMap {
    // Map of "search keyword" -> "devicon id"
    // Using -original.svg by default.
    val icons = mapOf(
        "java" to "java",
        "python" to "python",
        "javascript" to "javascript",
        "js" to "javascript",
        "typescript" to "typescript",
        "ts" to "typescript",
        "android" to "android",
        "kotlin" to "kotlin",
        "swift" to "swift",
        "flutter" to "flutter",
        "react" to "react",
        "vue" to "vue",
        "angular" to "angular",
        "node" to "nodejs",
        "nodejs" to "nodejs",
        "spring" to "spring",
        "docker" to "docker",
        "kubernetes" to "kubernetes",
        "k8s" to "kubernetes",
        "aws" to "amazonwebservices",
        "azure" to "azure",
        "firebase" to "firebase",
        "figma" to "figma",
        "git" to "git",
        "github" to "github",
        "gitlab" to "gitlab",
        "linux" to "linux",
        "ubuntu" to "ubuntu",
        "c++" to "cplusplus",
        "cpp" to "cplusplus",
        "c#" to "csharp",
        "csharp" to "csharp",
        "go" to "go",
        "golang" to "go",
        "rust" to "rust",
        "ruby" to "ruby",
        "php" to "php",
        "html" to "html5",
        "css" to "css3",
        "sass" to "sass",
        "tailwind" to "tailwindcss",
        "bootstrap" to "bootstrap",
        "mysql" to "mysql",
        "postgres" to "postgresql",
        "postgresql" to "postgresql",
        "mongo" to "mongodb",
        "mongodb" to "mongodb",
        "redis" to "redis",
        "sqlite" to "sqlite",
        "jira" to "jira",
        "trello" to "trello",
        "vscode" to "vscode",
        "intellij" to "intellij",
        "notion" to "notion" // Not in devicon usually, but let's check or keep out
        // Notion is not standard devicon. Removed.
    )
}
